function style_publication_axes(ax, cfg, fontSize)
%STYLE_PUBLICATION_AXES Apply proof-matched publication axis styling.
if nargin < 3 || isempty(fontSize)
    fontSize = cfg.fontSize;
end
set(ax, 'FontName', cfg.fontName, 'FontSize', fontSize, ...
    'LineWidth', cfg.axisLineWidth, 'TickDir', 'in', 'Box', 'on', ...
    'Layer', 'top', 'TickLabelInterpreter', 'none', ...
    'XGrid', 'on', 'YGrid', 'on', ...
    'GridColor', cfg.gridColor, 'GridAlpha', cfg.gridAlpha, ...
    'MinorGridColor', cfg.minorGridColor, ...
    'MinorGridAlpha', cfg.minorGridAlpha);
end
